#!/bin/sh
# postinst script for lumo

set -e

# Make sure the binary is executable
chmod 755 /usr/bin/lumo

# Create log directory if it doesn't exist
mkdir -p /var/log/lumo
chmod 755 /var/log/lumo

#DEBHELPER#

exit 0
